### ISSUE TITLE
change pins Attiny85

### ISSUE THREAD

**Issue by dontsovcmc** [puuu/USIWire#7]
I see in usi_io.h:
```
#  define PORT_USI_SDA PORTB0
#  define PORT_USI_SCL PORTB2
#  define PIN_USI_SDA PINB0
#  define PIN_USI_SCL PINB2
```

can I change them to another pins? 
I need 
```
#  define PORT_USI_SDA PORTB3
#  define PORT_USI_SCL PORTB4
#  define PIN_USI_SDA PINB3
#  define PIN_USI_SCL PINB4
```
thanks!

**Comment by puuu** [comment]
Unfortunately, no. The USI IOs are hard wired and there functions SDA/SCL are fix. The pins are described in the micro controller data sheets.
